### ISSUE TITLE
Load... (CTRL+L) changes current directory to Save folder

### ISSUE THREAD

**Issue by Frank-74** [project64/project64#1189]
Took a while to pin down what was causing the Static Interpreter config to be saved with default LLE settings to the Save folder.

Using Static Interpreter rsp, load a savestate with the Load... option, **rsp_conf.bin** will then be created in Save folder.  Load State (F7) is ok.

**Comment by project64** [comment]
so the dialog to choose the save state is changing the current dir. The problem with that RSP plugin it gets rsp_conf.bin from the current dir, not using a full path based of an .exe location .. I guess I could try to read the current dir before prompting then revert it after ...

but nothing should ever use the current dir as it is error prone as seen here

**Comment by Frank-74** [comment]
I've had GLideN64 write logs into the Save folder as well.

**Comment by LegendOfDragoon** [comment]
>I guess I could try to read the current dir before prompting then revert it after ...

That seems a bit extreme imo. I personally wouldn't bother trying to save and restore the current directory. I agree with you that nothing should use the current directory.

**Comment by project64** [comment]
I can make sure nothing in the project64 source uses current dir .. but if 3rd party plugins do it .. what can I do

**Comment by Frank-74** [comment]
I'm not sure this is a fault of PJ64.  I added config saving for Azimers 0.7 into the Project64\Config folder, and it doesn't break with CTRL+L.  I did nothing special to save the file.  It just works.  I don't know why cxd4's rsp saves it's bin file to different folders.  Azimer's 0.7 doesn't.

**Comment by cxd4** [comment]
>I can make sure nothing in the project64 source uses current dir ..

That seems a bit extreme imo.  I personally wouldn't bother trying to save and restore full directories.

>That seems a bit extreme imo. I personally wouldn't bother trying to save and restore the current directory.

I can make sure not to use platform-specific Win32 API features that change the standard current path while merely browsing other folders.  But if other non-portable programs depend on platform-specific code inside of "portable" C++ classes that do non-portable functions and hack standard Unix traits like the current path directory what can I do.

**Comment by project64** [comment]
I think the browse for folder dialog will potentially change the current dir to

**Comment by cxd4** [comment]
I assumed that's what he meant.  Ctrl+L IIRC is the keyboard shortcut for browsing for save states.

**Comment by Frank-74** [comment]
Yup, browsing for a folder (CTRL+L) changes the current directory.

**Comment by cxd4** [comment]
>I'm not sure this is a fault of PJ64.

I don't think it is either, and I don't think it isn't either.  Same logic with the plugin system.

I don't see why it matters whose fault it is.  I'm not adding platform-specific code just because somebody else is using platform-specific code; that's a lose-lose situation.  I won't do it.

**Comment by Frank-74** [comment]
> I don't think it is either.

Agreed....

It is a fault with the browse option that changes the Project64.exe location.  (Current directory).  It's the only way to create the problem.  But I wonder why it doesn't affect the config saving from my Azimer's branch.  I used C for the saving not C++, does this matter?

**Comment by cxd4** [comment]
I don't think that should matter, but I haven't done file I/O with C++ in a very long time.

I'm not familiar with the Win32 API so do not know whether there is any way to control the browse dialog to not modify the console's internal current working directory while browsing in Project64.  It might just be a built-in silly little feature of Windows.  Fixable by Project64 or not-fixable by Project64 I'm not adding nonstandard code because somebody else is relying on nonstandard code with the same nonstandardized behavior and results.

**Comment by cxd4** [comment]
If somebody else wants to PR it on the end of one of my plugins then that's mergeable if the platform-specificness is hidden away as cleanly as possible, but I don't see the cause for adding this myself.

**Comment by Frank-74** [comment]
All I'm doing in Azimer's to save the config is this;

`cpp
	int size;
	unsigned char *azicfg;
	FILE *file;
	file=fopen("Config/AziCfg.bin","ab+");
	fseek(file,0,SEEK_END);
    size=ftell(file);
	if(size == 0)
	{
		fprintf(file,"%c",1);	// PBO
		fprintf(file,"%c",0);	// Fix Sync
		fprintf(file,"%c",100);	// Volume
	}
	fseek(file,0,SEEK_SET);
	azicfg=(unsigned char*)malloc(size);
	fread(azicfg,size,1,file);
	fclose(file);

	snd->configPBO = azicfg[0];
	snd->configForceSync = azicfg[1];
	snd->configVolume = azicfg[2];
	free(azicfg);

**Comment by cxd4** [comment]
That is still using the standard C library for the file I/O.

It's not really different from what I'm doing, so if you're not seeing the issue with Azimer's just other plugins like mine then something in his classes is probably already doing the Win32-hacking to fix the current directory.  I don't know.

**Comment by project64** [comment]
file=fopen("Config/AziCfg.bin","ab+");

is a relative path .. I have found always using full paths fixes issues ..

**Comment by cxd4** [comment]
fopen("C:\Project64\Config/AziCfg.bin", "ab+"); isn't really any better.

It would fix fewer issues than it would cause.

**Comment by Frank-74** [comment]
I don't know, there is no problem with my Azimer's config saving into different folders.  Only the static interpreter rsp seems to have the problem.  And I don't know why.  My save, loads the file first from the Project64\config folder, if not found it writes a default.  It isn't affected by CTRL+L for some reason...

**Comment by cxd4** [comment]
Like I mentioned, you're not really doing anything different from what I'm doing in the RSP plugin.

The key thing is like me, you're using a relative path instead of an absolute path, like zilmar mentioned.  If you suspect there's something with your usage of the C stdio that's not causing the issue on Azimer's, you're welcome to try installing those changes to my RSP plugin, but I'm quite sure the result will be constant.  It's almost certainly something else being done by Azimer in his plugin before that function is called.

**Comment by Frank-74** [comment]
Append...

It does change the directory under certain conditions...

If I start a game, end emulation, CTRL+L, open audio settings, save settings, then it saves into the CTRL+L folder instead of the Project64.exe relative folder.

**Comment by cxd4** [comment]
I prematurely jumped over something you said earlier while reading.

You may be on to something there.  I do remember adding checks to create a default config file if it can't find one in the "current directory", but I'm not using append access.

At any rate, you can reduce the issue, but as long as you're using a relative path like me, the incompatibility is with Windows changing the current directory.  The browser dialogs are an optional little eye candy feature with many Windows programs like Project64; I'm not opposed to them per se, but standards conformance is not worth violating to bend over backwards for them.

**Comment by Frank-74** [comment]
I think plugins can only use relative paths...  It's upto windows/pj64 to maintain it.

**Comment by project64** [comment]
I can record the current dir before open the dialog, then reset the current dir post the open dialog .. but that does not guarantee the dialog is not shown in another plugin or could be added again somewhere

**Comment by Frank-74** [comment]
I think that is the best solution.  I doubt a plugin can initiate PJ64's browse for file.  If a plugin browses for a file, its upto it to maintain the relative directory.

**Comment by cxd4** [comment]
Well, it's not all Windows' fault either.

It can happen on UNIXes, too.

Let's say Project64 is installed to /home/users/me/project64/.

If you do this:
```
cd /home/users/me/project64/
./project64
```
... then Project64 (or more likely, the plugins running under it) think the current working directory is `/home/users/me/project64/`.

However, if you click a desktop shortcut to Project64, or don't change the current working directory, your command shell defaults to just your home folder.
```
# command window starts out at CD ~ or /home/users/me/
/home/users/me/project64/Project64 # starts Project64 using a full file path
```
This time, launching Project64 with a full path string to the Project64 executable, instead of changing the directory to where it is and calling it with a relative path (`./Project64`), leaves the current working directory unchanged from `~`, which breaks the assumption.

Is it a bug in plugins relying on relative paths in that case, too?  I think of it as a feature.  The user has the option to "configure" which path he or she wants Project64 to write and/or read its configuration files to and from.  If we hard-code a full directory path to fix the "issue" permanently they'll complain they need us to add a feature to let them change it.  If we don't have it hard-coded they'll complain that Project64 is wrong about the current directory when they're the ones who accidentally, unknowingly changed the current directory due to their lack of education.  zilmar is more concerned about the latter.

I just prefer keeping it simple.  It doesn't take much philosophy.  If anyone disagrees I can merge a PR to use a full-path with Win32-specific code but keep it out of the way from everything else please.

**Comment by project64** [comment]
does https://github.com/project64/project64/commit/52ab4949b40f8749230530873eede2daf9a624e6 help?

**Comment by Frank-74** [comment]
Fixed with https://github.com/project64/project64/commit/52ab4949b40f8749230530873eede2daf9a624e6 .

**Comment by cxd4** [comment]
You're still not keeping your commits very precise @project64.

That and the other commit Frank linked to about his mempak erasure issue ( https://github.com/project64/project64/commit/1d7bdd2c270c5ebde20da8d426223f9352668a3d ) look like they are committing multiple improvements in one commit.  Primarily in both commits it looks like you're simplifying the code by adding class members to reuse to cut down on code repetition and spamming, which is a good idea except it's obfuscating the desired target change implied by the commit's name/purpose.
