### ISSUE TITLE
Hey You, Pikachu! In-Game Audio

### ISSUE THREAD

**Issue by Ecksters** [project64/project64#1337]
None of the audio plugins I've tested seem to work completely properly with Hey You, Pikachu! In-game sounds.

Here's a couple hours of me playing, you can hear the audio issues right in the beginning:
https://www.twitch.tv/videos/159911960

I tried it with both shunyuan's HLE Audio and Jabo's DirectSound, with LLE and HLE settings where possible, shunyuan is what I'm using in that video, as it was less glitchy than Jabo.

Since GLideN64 has just added the Hey You, Pikachu! Microcodes, and the dual Raphnet USB Adapter works with the VRU, this game is now playable, so it'd be nice to see the audio working properly as well.

**Comment by vgturtle127** [comment]
@Ecksters Try with Azimer's audio and see if that helps.

**Comment by Ecksters** [comment]
Just tested Azimer, seems to give the same issue Jabu does, where the music just sounds super skippy non-stop, while shunyuan seems to have the music fine, but some of the character's sounds lag a ton.

**Comment by Ecksters** [comment]
What's especially odd to me is that apparently back when I was using PJ64 2.2 whatever the default audio was(I believe Jabu) seemed to work flawlessly:
https://youtu.be/f5asPaZJEQY?t=635

**Comment by loganmc10** [comment]
I don't have access to twitch where I am now, but I've tested this on both Project64 + Azmier's audio and mupen64plus and it sounds the same, choppy music mostly, and laggy voices.

Setting Counter Factor to 1 (CountPerOp in mupen64plus) makes it sound better/less choppy, but still not perfect.

**Comment by vgturtle127** [comment]
@Frank-74 Is there a regression in Project64? I figured it would be the audio plugin...

**Comment by loganmc10** [comment]
@Frank-74 Do you have the source/description for the changes you make to Azi Audio? It makes WDC sound much better

**Comment by Frank-74** [comment]
@vgturtle127 #984 caused Jabo to crackle.

@loganmc10 It's virtually no changes from current master with new audio code (XA2).  I'll have to double check.  I made the default buffer settings 4 buffers instead of 2.  I added a disable audiothread sleep (yield) option, which makes the audiothread process use too much CPU, but fixes slowdowns in a few games.  I added buffer settings in the config.  Buffer changes don't take affect until you reload or load a savestate.  The plugin has to re-init.

**Comment by Ecksters** [comment]
I replaced the .exe and still seem to be getting the same issue, with both audio plugins(using your new one). @Frank-74

**Comment by Frank-74** [comment]
@Ecksters Can you give me a savestate in the game with music/audio problem?

I cannot get into the game without the VRU.

Cheers.

@loganmc10 This is the only difference I can see between AziAudio master and mine:

```cpp
DWORD WINAPI XAudio2SoundDriver::AudioThreadProc(LPVOID lpParameter)
{
	XAudio2SoundDriver* driver = (XAudio2SoundDriver*)lpParameter;
	static int idx = 0;  // TODO: This needs to be moved...
	SetThreadPriority(driver->hAudioThread, THREAD_PRIORITY_HIGHEST);

	while (driver->bStopAudioThread == false)
	{
		if (g_source != NULL)
		{
			XAUDIO2_VOICE_STATE xvs;
			g_source->GetState(&xvs);
			// # of BuffersQueued is a knob we can turn for latency vs buffering
			// 2 is minimum.  Maximum is the size of bufferData which is still TBD (Current 5)
			// It is always possible to new a buffer prior to submission then free it on completion.  Worth it?
			while (xvs.BuffersQueued < 4) // Doubled this in hopes it would help... shouldn't cause too much additional latency
			{
				u32 len = driver->LoadAiBuffer(bufferData[idx], cacheSize);
				if (len > 0)
				{
					driver->PlayBuffer(bufferData[idx], len);
					idx = (idx + 1) % 4;
				}
				else
				{
					Sleep(1);
				}
				g_source->GetState(&xvs);
			}
		}
		if (Configuration::getForceSync() == false)
		{
			Sleep(1);
		}
		else
		{
			Sleep(0);
		}
	}
	return 0;
}
```

**Comment by Ecksters** [comment]
It appears to be a PJ64 regression, as version 2.2.0.3 has no audio problems, with your updated plugin, or Jabo, and I made sure I was using the same controller/GFX plugin as well to guarantee they aren't the issue.

However, the PJ64 Exe you gave me has the same regression as the official release.

**Comment by Ecksters** [comment]
I also want to note that even on v2.2.0.3, there is still an audio issue that may be audio plugin related. It creates a lot of in-game lag, I notice it particularly when you enter the Front Yard, looking at the doors or just when Pikachu looks at you seems to create it.

**Comment by Frank-74** [comment]
I noticed in the video you posted, the audio lag/stutter happens when there's an X over the speech icon.
Have you tried enabling disable audiothread sleep in my Azimer's plugin?

**Comment by LegendOfDragoon** [comment]
@Ecksters is Fixed Audio Timing enabled?

**Comment by Ecksters** [comment]
https://www.twitch.tv/videos/159935173
Youtube version if preferred: https://www.youtube.com/watch?v=bLc04BPT8Ps

That video was with "Disable AudioThread Sleep" checked, didn't seem to fix the issue.

@LegendOfDragoon Same issue if I Enable that, it was disabled for these videos though.

**Comment by Frank-74** [comment]
Also, in the build I posted above, I believe has Over Clock.  Set it to 2 (or 4 if your PC can handle it).  I do this for games with counter factor=2 setting.  It doesn't mess up the timing like setting counter factor to 1 when a game needs it set to 2.  But it has similar effect.

**Comment by LegendOfDragoon** [comment]
@Ecksters thanks for the feedback. I believe the regression is caused by the option "Fixed Audio Timing" being enabled by default. I'm pretty sure it was off by default in 2.2. If you want to use newer build of PJ64, just simply disable Fixed Audio Timing for this game.

I almost never use Fixed Audio Timing. I've only seen it beneficial for maybe a dozen games.

**Comment by Ecksters** [comment]
@LegendOfDragoon Ah, you are correct, the regression from 2.2 is due to Fixed Audio Timing.

However, the other issue I noted in the videos posted above is still present. @Frank-74 Setting it to both 2 and 4 I still get that issue.

**Comment by Frank-74** [comment]
@Ecksters The other issue being the severe stutter/lag?  It only happens when there's an X over the speech icon it seems?  So might be to do with the VRU/microphone on/off detection.  It seems to make everything stall, I don't believe that's caused by an audio problem.  Something wrong in the input plugin perhaps?

**Comment by Ecksters** [comment]
@Frank-74 In [the video](https://www.youtube.com/watch?v=bLc04BPT8Ps) I just posted the speech icon is always available, it seems to actually lag whenever the two dialogues on the sides show up.

**Comment by Ecksters** [comment]
For good measure, I just tested it with NRage instead of my plugin (no VRU at all), and that appears to be the issue. I'll post this on that plugin's page so they know. Thanks everyone!

**Comment by Ecksters** [comment]
https://github.com/raphnet/pj64raphnetraw/issues/3
