### ISSUE TITLE
Build fails.

### ISSUE THREAD

**Issue by JunielKatarn** [project64/project64#1412]
As of commit 1178b5c73fa054c329c11d769374e5d50928eaea, a regular (x86|Debug) build fails with the following message:
```
"D:\Extra\pj64\buildme\Project64.sln" (default target) (1) ->
       "D:\Extra\pj64\buildme\Source\nragev20\NRage_Input_V2.vcxproj" (default target) (8) ->
       (PreBuildEvent target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073:
        The command ""D:\Extra\pj64\buildme\Source\Script\UpdateVersion.cmd" "Debug" "D:\Extra\pj64\buildme\Source\nragev20\Version.h.in" "D:\Extra
       \pj64\buildme\Source\nragev20\Version.h"\r [D:\Extra\pj64\buildme\Source\nragev20\NRage_Input_V2.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :
       VCEnd" exited with code 1. [D:\Extra\pj64\buildme\Source\nragev20\NRage_Input_V2.vcxproj]
```

It may be related to this program: `UpdateVersion.exe`.

**Comment by project64** [comment]
hopefully the last few commits fix it

**Comment by JunielKatarn** [comment]
Some errors were fixed, but seems like Android now breaks:
```
"D:\Build\pj64\buildme\Project64.sln" (default target) (1) ->
"D:\Build\pj64\buildme\Source\Android\Bridge\Bridge.vcxproj" (default target) (4) ->
(ClCompile target) ->
  jniBridge.cpp(19): fatal error C1083: Cannot open include file: 'Project64-core/Version.h': No such file or directory [D:\Build\pj64\buildme\Source\Android\Bridge\Bridge.vcxproj]
```

As a side note, if Android is actually built with another set of tools (Android Studio, right?), why not just leave it out of the Visual Studio build? It would make things faster and easier to maintain on the Windows side.

**Comment by project64** [comment]
sounds like build order, need to make sure Bridge.vcxproj has a dependency on Project64-core so that the version is created first before bridge is built

**Comment by project64** [comment]
https://github.com/project64/project64/commit/28741a0367580286e509b66534253731e116195e

this should fix the bridge, any other issues?

**Comment by JunielKatarn** [comment]
It still fails due to the UpdateVersion exe being invoked before it gets built.
#1414 fixes this.
Can you take a look?

**Comment by project64** [comment]
this is cause your not using the solution to build? just the project files?

**Comment by JunielKatarn** [comment]
It fails in both cases. This makes sense, because right now there is no enforcement of build dependencies.
UpdateVersion should be a build dependency for any projects that need its compiled EXE.

The PR #1414 fixes this without any side effects.

**Comment by project64** [comment]
the solution should build fine, as there is dependencies on UpdateVersion.exe so UpdateVersion exe will be built first. Your change is to add a reference. The major difference between the dependency and the reference here is that the dependency is described in the solution where the reference is in the project settings.

**Comment by JunielKatarn** [comment]
Right, but the Solution-based dependency will only be enforced by the Visual Studio IDE (meaning, you need to have the editor open to successfully build).
The reference works for non-IDE builds too.
Both can co-exist, but non-IDE builds need a fix.

**Comment by cxd4** [comment]
Non-IDE builds work just fine in my experience, with no errors.  Of course the resulting build doesn't run very well since the path stuff and GUI isn't ported to Linux for the time.

**Comment by JunielKatarn** [comment]
@project64 
Found the issue. The git command used in UpdateVersion.cmd works if you clone the main repository (project64/project64.git), but not forks (myuser/project64.git).
It's not possible to work around it because UpdateVersion.cmd is always called and the command is hard-coded.

I added #1416 addressing this.
Let me know if you have any feedback.

**Comment by project64** [comment]
I understand if your building the projects outside of the solution, as the solution contains the dependency to build update version first. But I do not understand why a fork work fail if built with the solution.

**Comment by JunielKatarn** [comment]
@project64 The tags issue has been clarified, but there's still the build order problem.
Will you consider merging #1414, or should I just close it?
As a reminder, that change doesn't have any side-effects on both IDE and non-IDE Windows builds.

**Comment by project64** [comment]
I want to double check and have not had the time, but if references as added then the dependencies should be removed

**Comment by JunielKatarn** [comment]
Agreed.

**Comment by wfowler1** [comment]
May or may not be the same issue, but I'm still having issues building within VS. It seems UpdateVersion still isn't building properly. Specifically the UpdateVersion.cmd script isn't working.

> Error MSB3073 The command ""C:\Users\Will\Documents\project64\Source\Script\UpdateVersion.cmd" "Release" "C:\Users\Will\Documents\project64\Source\Project64-video\Version.h.in" "C:\Users\Will\Documents\project64\Source\Project64-video\Version.h"
:VCEnd" exited with code -1073740791.	Project64-video	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	123	

This error repeats for projects "RSP" "Project64-audio" "PJ64 NRage" and "Project64-core". Since Version.h is never generated the build simply fails.

**Comment by JunielKatarn** [comment]
I think instead of generating and parsing/editing a file, the version number should be a compiler-level variable that can be passed to MSBuild.

That should make non-release builds easier.

**Comment by PartyPlanner64** [comment]
I encountered this issue, it was resolved by doing the following:

- Making sure `git` is in the `PATH`
- Make sure you check out `project64` as a git repository so you have `.git`, rather than downloading a repo zip.

It seems this issue could be resolved either by adjusting the build to work if `UpdateVersion.cmd` fails, or documenting the above on the build wiki.

**Comment by project64** [comment]
if you download instead of cloning .. then how is it meant to know the version number .. maybe there is a way to detect that git is not there via command line and give it something wrong for the version number

**Comment by JunielKatarn** [comment]
It would be ideal for the git-inferred version number to not be mandatory for building.
We could define a macro variable to provide a default build number in case the git commands fail.

**Comment by oddMLan** [comment]
Cannot reproduce, x86 debug build compiles just fine now.
If you're having trouble with UpdateVersion.exe make sure you cloned the repo correctly to a folder and that you fetch the repo tags as well. If you omit tag fetching, UpdateVersion doesn't work, which makes compilation fail.
