### ISSUE TITLE
[Bug]: Black screen on every game; no video and audio

### ISSUE THREAD

**Issue by Rex000** [project64/project64#2422]
### Expected behavior?

Game should run properly with video and audio

### Actual behavior?

No video and audio

### Steps to reproduce the problem

1. Start any game
2.
3.
4.
5.
...

### Error messages?

No message

### What game were you playing?

Title:

Nintendo 64 game or Nintendo 64 Disk Drive:

ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
Save type: (attach game save or save state here)

Original or modified ROM?:(attach patch if applicable here)

### Specifications and build details

Project64: Dev-4.0.0-6393-3baaa82

OS: Win 10 22H2

CPU: i5 3570K

RAM: 8 GB

Graphics: GTX 1080

### Using included plugins

- [X] I can confirm I am using the included RSP, audio, input, and graphics plugins

### Plugins used while the issue occurred

All default plugins and settings

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
fill the form properly.

**Comment by Rex000** [comment]
I've filled it to the best of my ability. Is there anything in particular that you need?

**Comment by project64** [comment]
First and foremost, this is not a support forum.

I'm not sure which version of Project64 you are using. 

Is your issue occurs with everything or just something specific? 
Does it run using the interpreter? 
Is it related to the graphics plugin?

**Comment by Rex000** [comment]
I have already provided the build number in the topic.

I have checked again. Most games outright give a black screen, while some like Super Mario 64 show the first screen with the logo and then a black screen afterwards.

I've changed it to interpreter as well as changed the graphics plugin as well, but still the same.

I'd also like to mention that v3.0.1 doesn't seem to have this issue.

**Comment by Squall-Leonhart** [comment]
Title should've been no video, but audio.

**Comment by Squall-Leonhart** [comment]
Interpreter works though, so no idea what you're testing.

**Comment by Squall-Leonhart** [comment]
Fixed in latest nightly.

**Comment by Rex000** [comment]
There was neither any audio nor video. And like I said none of this happens in 3.0.1. You can try for example Banjo Kazooie.

**Comment by RageCage64** [comment]
I am still having this problem on the latest nightly.

Issue happened on any included video plugin (I always restarted after changing the plugin). I am otherwise only using included plugins; this is off a fresh install.

ROM is an unmodified Banjo-Kazooie v1.0. Can provide more ROM info if necessary but none of the ones I had seem to be working.

No saves; first boot on this installation.

Project64 Version: Dev-4.0.0-6396-77ac474
OS: Windows 11 Home 23H2
CPU: AMD Ryzen 5 3600
RAM: 32 GB
Graphics: AMD Radeon RX 5700 XT
